volumes:
  spool-slurmctld:
    external: false
  etc-slurm:
    external: false
  home:
    external: false

x-common-volumes: &common-volumes
  - spool-slurmctld:/var/spool/slurmctld
  - etc-slurm:/etc/slurm
  - home:/home

x-env-var: &env-var
  - SLURMCTLD_HOSTS=slurm-container-master
  - CLUSTERNAME=test

x-slurm-container: &slurm-container
  image: localhost/slurm:${TAG:-el9}
  build:
    context: .
    dockerfile: ${TAG:-el9}/Containerfile
  volumes: *common-volumes
  privileged: true
  environment: *env-var

services:
  master:
    <<: *slurm-container
    hostname: slurm-container-master
    container_name: slurm-container-master
    command: --role slurmctld

  compute:
    <<: *slurm-container
    command: --role slurmd
    deploy:
      mode: replicated
      replicas: 2
