volumes:
  spool-slurmctld:
    external: false
  etc-slurm:
    external: false
  home:
    external: false
  slurm_acct_db:
    external: false


x-common-volumes: &common-volumes
  - spool-slurmctld:/var/spool/slurmctld
  - etc-slurm:/etc/slurm
  - home:/home

x-database-volumes: &database-volumes
  - slurm_acct_db:/var/lib/mysql

# All these variable are required for initialising database and cluster configure. Once the cluster has initialised, it follows the configuration saved in the volumes on restart. 
x-init-var: &init-var
  - SLURMCTLD_HOSTS=slurm-container-master-1,slurm-container-master-2
  - SLURMDBD_HOSTS=slurm-container-slurmdb-1,slurm-container-slurmdb-2
  - CLUSTERNAME=demo
  - MYSQL_PASSWORD=password
  - MYSQL_USER=slurm
  - MYSQL_DATABASE=slurm_acct_db
  - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - SLURMDBD_STORAGEHOST=slurm-container-db
  # - CONFIGLESS=on

x-slurm-container: &slurm-container
  image: localhost/slurm:${TAG:-el9}
  build:
    context: .
    dockerfile: ${TAG:-el9}/Containerfile
  volumes: *common-volumes
  privileged: true
  environment: *init-var
  restart: on-failure:10

services:
  mariadb:
    image: mariadb:lts
    container_name: slurm-container-db
    hostname: slurm-container-db
    volumes: *database-volumes
    environment: *init-var
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"

  slurmdb-1:
    <<: *slurm-container
    hostname: slurm-container-slurmdb-1
    container_name: slurm-container-slurmdb-1
    command: --role slurmdbd
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6819  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
    depends_on:
      mariadb:
        condition: service_healthy

  slurmdb-2:
    <<: *slurm-container
    hostname: slurm-container-slurmdb-2
    container_name: slurm-container-slurmdb-2
    command: --role slurmdbd
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6819  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
      start_period: 5s
    depends_on:
      mariadb:
        condition: service_healthy

  master-1:
    <<: *slurm-container
    hostname: slurm-container-master-1
    container_name: slurm-container-master-1
    command: --role slurmctld
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6817  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
      start_period: 5s
    depends_on:
      slurmdb-1:
        condition: service_healthy

  master-2:
    <<: *slurm-container
    hostname: slurm-container-master-2
    container_name: slurm-container-master-2
    command: --role slurmctld
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6817  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
      start_period: 5s
    depends_on:
      slurmdb-1:
        condition: service_healthy

  compute:
    <<: *slurm-container
    command: --role slurmd
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6818  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
      start_period: 5s
    depends_on:
      master-1:
        condition: service_healthy
  
  api:
    <<: *slurm-container
    command: --role slurmrestd
    healthcheck:
      test: ["CMD-SHELL", "until nc -z localhost 6820  ; do sleep 10 ; done"]
      timeout: 72h
      interval: 5m
      start_period: 5s
    depends_on:
      master-1:
        condition: service_healthy
  
  client:
    <<: *slurm-container
    command: --role sackd
    depends_on:
      master-1:
        condition: service_healthy

networks:
  default: {}
