volumes:
  spool-slurmctld:
    external: false
  etc-slurm:
    external: false
  home:
    external: false
  slurm_acct_db:
    external: false


x-common-volumes: &common-volumes
  - spool-slurmctld:/var/spool/slurmctld
  - etc-slurm:/etc/slurm
  - home:/home

x-database-volumes: &database-volumes
  - slurm_acct_db:/var/lib/mysql

# All these variable are required for initialising database and cluster configure. Once the cluster has initialised, it follows the configuration saved in the volumes on restart. 
x-init-var: &init-var
  - SLURMCTLD_HOSTS=slurm-container-master
  - SLURMDBD_HOSTS=slurm-container-slurmdb
  - CLUSTERNAME=demo
  - MYSQL_PASSWORD=password
  - MYSQL_USER=slurm
  - MYSQL_DATABASE=slurm_acct_db
  - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - SLURMDBD_STORAGEHOST=slurm-container-db

x-slurm-container: &slurm-container
  image: docker.io/csniper/slurm:${TAG:-24.05}
  volumes: *common-volumes
  privileged: true
  environment: *init-var

services:
  mariadb:
    image: mariadb:lts
    container_name: slurm-container-db
    hostname: slurm-container-db
    volumes: *database-volumes
    environment: *init-var
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"

  slurmdb:
    <<: *slurm-container
    hostname: slurm-container-slurmdb
    container_name: slurm-container-slurmdb
    command: --role slurmdbd
    healthcheck:
      test: "nc -z localhost 6819"
    depends_on:
      mariadb:
        condition: service_healthy

  master:
    <<: *slurm-container
    hostname: slurm-container-master
    container_name: slurm-container-master
    command: --role slurmctld
    healthcheck:
      test: "nc -z localhost 6817"
    depends_on:
      slurmdb:
        condition: service_healthy
        
  compute:
    <<: *slurm-container
    command: --role slurmd
    healthcheck:
      test: "nc -z localhost 6818"
    depends_on:
      master:
        condition: service_healthy
  
  api:
    <<: *slurm-container
    command: --role slurmrestd
    healthcheck:
      test: "nc -z localhost 6820"
    depends_on:
      master:
        condition: service_healthy

networks:
  default: {}
