FROM docker.io/library/maven:3.8.7-openjdk-18-slim AS build-jwk-generator
COPY json-web-key-generator /build
WORKDIR /build
RUN mvn package
# Build the app
# Artifact will be stored at /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar
# RUN java -jar /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar --type RSA --size 2048 --algorithm RS256 --idGenerator sha1 --keySet --output /jwks.json --pubKeyOutput /jwks.pub.json

FROM quay.io/rockylinux/rockylinux:9 as build
# Build slurm
COPY el9/*.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-rpm.sh

# Build entrypoint 
COPY common/entrypoint.m4 common/build-entrypoint.sh ./
RUN ./build-entrypoint.sh

FROM quay.io/rockylinux/rockylinux:9
COPY --from=build /opt/slurm-repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY --from=build /opt/entrypoint /opt/local/bin/entrypoint
COPY common/*.j2 LICENSE /opt/local/

RUN dnf -y install yum-utils epel-release \
	&& dnf config-manager --enable crb \
	&& dnf -y install slurm-slurmctld slurm-slurmd slurm-slurmdbd slurm-slurmrestd slurm-sackd slurm-example-configs slurm-contribs slurm-devel slurm-libpmi slurm-pam_slurm java-latest-openjdk java-latest-openjdk-devel sudo nc xorg-x11-xauth hostname \
	&& dnf clean all

# create slurm user
RUN useradd -r -b /var/lib slurm \
	&& useradd -r -b /var/lib -s /usr/sbin/nologin slurmrestd

# set up jinja2-cli 
RUN python3 -m venv /opt/local && /opt/local/bin/python3 -m pip install jinja2-cli 

# set up json-web-key-generator
COPY --from=build-jwk-generator /build/target/json-web-key-generator-0.9-SNAPSHOT-jar-with-dependencies.jar /opt/local/lib/json-web-key-generator.jar

# start slurmd via systemd
COPY common/slurmd-extra.conf /etc/systemd/system/slurmd.service.d/
RUN ln -sf /lib/systemd/system/multi-user.target /etc/systemd/system/default.target \
	&& ln -s /usr/lib/systemd/system/slurmd.service /etc/systemd/system/multi-user.target.wants/ \
	&& rm -f /etc/systemd/system/systemd-logind.service 

# Expose port used by slurm
EXPOSE 6817-6820

ENTRYPOINT [ "/opt/local/bin/entrypoint" ]