
FROM docker.io/library/debian:12 as build
# Build slurm
COPY deb12/*.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-deb.sh

# Build entrypoint 
COPY common/entrypoint.m4 common/build-entrypoint.sh ./
RUN ./build-entrypoint.sh

FROM docker.io/library/debian:12-slim
COPY --from=build /opt/slurm-repo /opt/slurm-repo
COPY --from=build /etc/apt/sources.list.d/slurm.list /opt/slurm-repo
COPY --from=build /etc/apt/sources.list.d/slurm.list /etc/apt/sources.list.d/slurm.list
COPY --from=build /opt/entrypoint /opt/local/bin/entrypoint
COPY common/slurm-token /opt/local/bin/slurm-token
COPY common/*.j2 LICENSE /opt/local/

RUN apt-get -y update \
	&& apt-get -y install --no-install-recommends curl gpg ca-certificates \
	&& install -m 0755 -d /etc/apt/keyrings \
	&& curl -fsSL https://packages.smallstep.com/keys/apt/repo-signing-key.gpg -o /etc/apt/keyrings/smallstep.asc \
	&& printf "Types: deb\nURIs: https://packages.smallstep.com/stable/debian\nSuites: debs\nComponents: main\nSigned-By: /etc/apt/keyrings/smallstep.asc\n" > /etc/apt/sources.list.d/smallstep.sources \
	&& apt-get -y update \
	&& apt-get -y install slurm-smd-client slurm-smd-slurmd slurm-smd-slurmctld slurm-smd-slurmdbd slurm-smd-slurmrestd slurm-smd-sackd slurm-smd-sview slurm-smd-doc slurm-smd-dev slurm-smd-libpmi0 slurm-smd-libpmi2-0 slurm-smd-libnss-slurm slurm-smd-libpam-slurm-adopt systemd systemd-sysv step-cli jq python3 python3-pip python3-dev python3-venv libpython3-dev libpython3-stdlib sudo netcat-traditional xauth hostname \
	&& apt-get clean

# create slurm user
RUN useradd -r -b /var/lib slurm \
	&& useradd -r -b /var/lib -s /usr/sbin/nologin slurmrestd

# set up jinja2-cli 
RUN python3 -m venv /opt/local && /opt/local/bin/python3 -m pip install jinja2-cli

# start slurmd via systemd
COPY common/slurmd-extra.conf /etc/systemd/system/slurmd.service.d/
RUN ln -sf /lib/systemd/system/multi-user.target /etc/systemd/system/default.target \
	&& ln -sf /usr/lib/systemd/system/slurmd.service /etc/systemd/system/multi-user.target.wants/ \
	&& rm -f /etc/systemd/system/systemd-logind.service \
	&& mkdir -pv /etc/sysconfig/

# Expose port used by slurm
EXPOSE 6817-6820

ENTRYPOINT [ "/opt/local/bin/entrypoint" ]