
FROM quay.io/rockylinux/rockylinux:8 as build
# Build slurm
COPY el8/*.sh ./
COPY slurm ./slurm-src
RUN ./build-slurm-rpm.sh

# Build entrypoint 
COPY common/entrypoint.m4 common/build-entrypoint.sh ./
RUN ./build-entrypoint.sh

FROM quay.io/rockylinux/rockylinux:8
COPY --from=build /opt/slurm-repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /opt/slurm-repo
COPY --from=build /etc/yum.repos.d/slurm.repo /etc/yum.repos.d/slurm.repo
COPY --from=build /opt/entrypoint /opt/local/bin/entrypoint
COPY common/slurm-token /opt/local/bin/slurm-token
COPY common/*.j2 LICENSE /opt/local/

RUN printf "[smallstep]\nname=Smallstep\nbaseurl=https://packages.smallstep.com/stable/fedora/\nenabled=1\nrepo_gpgcheck=0\ngpgcheck=0\n" > /etc/yum.repos.d/smallstep.repo \
	&& yum install -y yum-utils epel-release \
	&& yum-config-manager --enable powertools \
	&& yum install -y slurm-slurmctld slurm-slurmd slurm-slurmdbd slurm-slurmrestd slurm-sackd slurm-example-configs slurm-contribs slurm-devel slurm-libpmi slurm-pam_slurm step-cli jq python3 sudo nc xorg-x11-xauth hostname \
	&& yum -y update \
	&& yum clean all

# create slurm user
RUN useradd -r -b /var/lib slurm \
	&& useradd -r -b /var/lib -s /usr/sbin/nologin slurmrestd

# set up jinja2-cli 
RUN python3 -m venv /opt/local && /opt/local/bin/python3 -m pip install jinja2-cli

# start slurmd via systemd
COPY common/slurmd-extra.conf /etc/systemd/system/slurmd.service.d/
RUN ln -sf /lib/systemd/system/multi-user.targßet /etc/systemd/system/default.target \
	&& ln -s /usr/lib/systemd/system/slurmd.service /etc/systemd/system/multi-user.target.wants/ \
	&& rm -f /etc/systemd/system/systemd-logind.service 

# Expose port used by slurm
EXPOSE 6817-6820

ENTRYPOINT [ "/opt/local/bin/entrypoint" ]